sudo: required                                                                                                                                                                                                                                 
language: go
services:
  - docker

script:
  - docker build -t homie-intercom:build-$TRAVIS_COMMIT -f Dockerfile.build . ;
  - docker run homie-intercom:build-$TRAVIS_COMMIT /usr/local/bin/get-artifact > homie-intercom;
deploy:
  provider: releases
  api_key: ""
  file: homie-intercom
  skip_cleanup: true
  on:
    tags: true
